version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ia-microservice-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ia-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ia_microservice
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis

  db:
    image: postgres:15-alpine
    container_name: ia-microservice-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ia_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ia-network
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: ia-microservice-redis
    restart: unless-stopped
    networks:
      - ia-network
    ports:
      - "6380:6379"

  nginx:
    image: nginx:alpine
    container_name: ia-microservice-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ia-network
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local

networks:
  ia-network:
    driver: bridge
